// src/components/statistics/Statistics.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import ky from 'ky';
    import { useMachine } from '@xstate/svelte';
    import { icons } from 'feather-icons';
    import { createStatisticsStateMachine } from './state-machine';
    import YearsInBusiness from './YearsInBusiness.svelte';
    import GitHubRepositories from './GitHubRepositories.svelte';
    import GitHubStars from './GitHubStars.svelte';
    import Figure from './Figure.svelte';

    const currentTimestamp = import.meta.env.PROD ? new Date() : new Date(2022, 2, 23);
    const gitHubStateMachine = createStatisticsStateMachine({ ky, currentTimestamp });

    const { state, send } = useMachine(gitHubStateMachine);

    onMount(() => {
        send('FETCH');
    });
</script>

<YearsInBusiness state={$state} />
<GitHubRepositories state={$state} />
<GitHubStars state={$state} />
<Figure description="Lines of Code">
    {@html icons['bar-chart']?.toSvg({ class: 'text-dracula-green w-6 h-6 mt-2' })}
</Figure>

// src/statistics/Statistics.tsx
import React, { FunctionComponent, useEffect } from 'react';
import { useMachine } from '@xstate/react';
import { FiBarChart, FiBarChart2 } from 'react-icons/fi';
import { StatisticsStateMachine, StatisticsStateMachineState } from './state-machine';
import { Figure } from './Figure';
import { GitHubStars } from './GitHubStars';
import { GitHubRepositories } from './GitHubRepositories';
import { YearsInBusiness } from './YearsInBusiness';

interface StatisticsProps {
    readonly statisticsStateMachine: StatisticsStateMachine;
}

function renderStatistics(state: StatisticsStateMachineState): JSX.Element {
    return (
        <section className="bg-dracula-dark p-4 lg:p-10">
            <h3 className="flex items-center lg:items-end justify-center gap-x-2 text-dracula-cyan lg:leading-none text-2xl lg:text-4xl font-extrabold my-2">
                Some Stats
                <FiBarChart2 className="text-dracula-light w-6 h-6 lg:w-9 lg:h-9" />
            </h3>
            <hr className="h-2 w-1/2 border-none mb-4 m-auto bg-dracula-red bg-gradient-to-br from-yellow to-dracula-pink rounded-lg" />
            <div className="m-auto max-w-screen-lg grid gap-2 sm:gap-4 grid-cols-2 lg:grid-cols-4 sm:p-4">
                <YearsInBusiness state={state} />
                <GitHubRepositories state={state} />
                <GitHubStars state={state} />
                <Figure description="Lines of Code">
                    <FiBarChart className="text-dracula-green w-6 h-6 mt-2" />
                </Figure>
            </div>
        </section>
    );
}

export const Statistics: FunctionComponent<StatisticsProps> = (props) => {
    const { statisticsStateMachine } = props;
    const [state, send] = useMachine(statisticsStateMachine);

    useEffect(() => {
        send('FETCH');
    }, []);

    return renderStatistics(state);
};
