// src/components/statistics/YearsInBusiness.svelte
<script lang="ts">
    import type { StatisticsStateMachineState } from './state-machine';
    import Figure from './Figure.svelte';
    import Cite from './Cite.svelte';

    export let state: StatisticsStateMachineState;
</script>

{#if state.context.yearsOfExperience.isJust}
    <Figure description="Experience">
        <Cite ariaLabel="Years of experience">{state.context.yearsOfExperience.value} yrs</Cite>
    </Figure>
{/if}

// src/statistics/YearsInBusiness.tsx
import React, { FunctionComponent } from 'react';
import { Cite } from './Cite';
import { Figure } from './Figure';
import { StatisticsStateMachineState } from './state-machine';

export interface YearsInBusinessProps {
    readonly state: StatisticsStateMachineState;
}

export const YearsInBusiness: FunctionComponent<YearsInBusinessProps> = (props) => {
    const { state } = props;
    return (
        <Figure description="Experience">
            <Cite>{state.context.yearsOfExperience.value} yrs</Cite>
        </Figure>
    );
};
