// source/statistics/GitHubStars.tsx
import type { FunctionComponent, ReactNode } from "react";
import type { Maybe } from "true-myth";
import type { GitHubStatistics } from "../github-statistics/github-statistics-schema";
import { StatisticsFigure } from "./StatisticsFigure.js";
import { LoadingSpinner } from "./LoadingSpinner.js";
import { StatisticsCite } from "./StatisticsCite.js";

type Properties = {
	readonly isFetching: boolean;
	readonly githubStatistics: Maybe<GitHubStatistics>;
};

function renderLoadingSpinner(isFetching: boolean): ReactNode {
	if (isFetching) {
		return <LoadingSpinner />;
	}

	return null;
}

function renderStatisticsCite(isFetching: boolean, githubStatistics: Maybe<GitHubStatistics>): ReactNode {
	if (isFetching) {
		return null;
	}

	return (
		<StatisticsCite description="GitHub Stars">
			{githubStatistics.get("user").get("starredRepositories").get("totalCount").unwrapOr(0)}
		</StatisticsCite>
	);
}

export const GitHubStars: FunctionComponent<Properties> = (properties) => {
	const { isFetching, githubStatistics } = properties;

	return (
		<StatisticsFigure description="GitHub Stars">
			{renderLoadingSpinner(isFetching)}

			{renderStatisticsCite(isFetching, githubStatistics)}
		</StatisticsFigure>
	);
};

// source/statistics/GitHubStars.vue
<script setup lang="ts">
import type { Maybe } from "true-myth";
import type { GitHubStatistics } from "../github-statistics/github-statistics-schema";
import StatisticsFigure from "./StatisticsFigure.vue";
import LoadingSpinner from "./LoadingSpinner.vue";
import StatisticsCite from "./StatisticsCite.vue";

type Properties = {
	readonly isFetching: boolean;
	readonly githubStatistics: Maybe<GitHubStatistics>;
};

const { isFetching, githubStatistics } = defineProps<Properties>();
</script>

<template>
	<StatisticsFigure description="GitHub Stars">
		<LoadingSpinner v-if="isFetching" />

		<StatisticsCite v-if="!isFetching" description="GitHub Stars">
			{{ githubStatistics.get("user").get("starredRepositories").get("totalCount").unwrapOr(0) }}
		</StatisticsCite>
	</StatisticsFigure>
</template>
