// src/statistics/GitHubRepositories.tsx
import React, { FunctionComponent } from 'react';
import { FiAlertTriangle } from 'react-icons/fi';
import { Cite } from './Cite';
import { Figure } from './Figure';
import { LoadingSpinner } from './LoadingSpinner';
import { StatisticsStateMachineState } from './state-machine';

interface GitHubRepositoriesProps {
    readonly state: StatisticsStateMachineState;
}

export const GitHubRepositories: FunctionComponent<GitHubRepositoriesProps> = (props) => {
    const { state } = props;
    let gitHubRepositories: JSX.Element | number = <LoadingSpinner />;
    if (state.matches('loaded')) {
        gitHubRepositories = state.context.gitHubStatistics.value.user.repositories.totalCount;
    } else if (state.matches('failed')) {
        gitHubRepositories = <FiAlertTriangle />;
    }
    return (
        <Figure description="GitHub Repos">
            <Cite>{gitHubRepositories}</Cite>
        </Figure>
    );
};

// source/statistics/GitHubRepositories.svelte
<script lang="ts">
	import { icons } from "feather-icons";
	import Cite from "./Cite.svelte";
	import Figure from "./Figure.svelte";
	import LoadingSpinner from "./LoadingSpinner.svelte";
	import type { StatisticsStateMachineState } from "./state-machine";

	export let state: StatisticsStateMachineState;
</script>

<Figure description="GitHub Repos">
	<Cite ariaLabel="GitHub Repos">
		{#if state.matches("loaded")}
			{state.context.gitHubStatistics.value.user.repositories.totalCount}
		{:else if state.matches("failed")}
			{@html icons["alert-triangle"]?.toSvg()}
		{:else}
			<LoadingSpinner />
		{/if}
	</Cite>
</Figure>
