// source/statistics/GitHubRepositories.tsx
import type { FunctionComponent, ReactNode } from "react";
import { icons } from "feather-icons";
import type { StatisticsStoreState } from "./statistics-store";
import { Cite } from "./Cite";
import { Figure } from "./Figure";
import { LoadingSpinner } from "./LoadingSpinner";

interface GitHubRepositoriesProperties {
	readonly fetchGitHubStatisticsState: StatisticsStoreState["fetchGitHubStatisticsState"];
	readonly gitHubStatistics: StatisticsStoreState["gitHubStatistics"];
}

function renderTotalCount(properties: GitHubRepositoriesProperties): ReactNode {
	const { fetchGitHubStatisticsState, gitHubStatistics } = properties;

	if (fetchGitHubStatisticsState === "idle" || fetchGitHubStatisticsState === "loading") {
		return <LoadingSpinner />;
	}

	if (fetchGitHubStatisticsState === "error") {
		return <figure dangerouslySetInnerHTML={{ __html: icons["alert-triangle"]?.toSvg() }} />;
	}

	if (fetchGitHubStatisticsState === "loaded" && gitHubStatistics.isJust) {
		return gitHubStatistics.value.user.repositories.totalCount;
	}

	return null;
}

export const GitHubRepositories: FunctionComponent<GitHubRepositoriesProperties> = (properties) => {
	return (
		<Figure description="GitHub Repos">
			<Cite ariaLabel="GitHub Repos">{renderTotalCount(properties)}</Cite>
		</Figure>
	);
};

// source/statistics/GitHubRepositories.svelte
<script lang="ts">
	import { icons } from "feather-icons";
	import Figure from "./Figure.svelte";
	import Cite from "./Cite.svelte";
	import LoadingSpinner from "./LoadingSpinner.svelte";
	import type { StatisticsStoreState } from "./statistics-store";

	export let fetchGitHubStatisticsState: StatisticsStoreState["fetchGitHubStatisticsState"];
	export let gitHubStatistics: StatisticsStoreState["gitHubStatistics"];
</script>

<Figure description="GitHub Repos">
	<Cite ariaLabel="GitHub Repos">
		{#if fetchGitHubStatisticsState === "idle" || fetchGitHubStatisticsState === "loading"}
			<LoadingSpinner />
		{:else if fetchGitHubStatisticsState === "error"}
			<figure>
				{@html icons["alert-triangle"]?.toSvg()}
			</figure>
		{:else if fetchGitHubStatisticsState === "loaded" && gitHubStatistics.isJust}
			{gitHubStatistics.value.user.repositories.totalCount}
		{/if}
	</Cite>
</Figure>
