// src/statistics/GitHubStars.tsx
import React, { FunctionComponent } from 'react';
import { FiAlertTriangle } from 'react-icons/fi';
import { Cite } from './Cite';
import { Figure } from './Figure';
import { LoadingSpinner } from './LoadingSpinner';
import { StatisticsStateMachineState } from './state-machine';

interface GitHubStarsProps {
    readonly state: StatisticsStateMachineState;
}

export const GitHubStars: FunctionComponent<GitHubStarsProps> = (props) => {
    const { state } = props;
    let gitHubStars: JSX.Element | number = <LoadingSpinner />;
    if (state.matches('loaded')) {
        gitHubStars = state.context.gitHubStatistics.value.user.starredRepositories.totalCount;
    } else if (state.matches('failed')) {
        gitHubStars = <FiAlertTriangle />;
    }

    return (
        <Figure description="GitHub Stars">
            <Cite>{gitHubStars}</Cite>
        </Figure>
    );
};

// source/statistics/GitHubStars.svelte
<script lang="ts">
	import { icons } from "feather-icons";
	import Cite from "./Cite.svelte";
	import Figure from "./Figure.svelte";
	import LoadingSpinner from "./LoadingSpinner.svelte";
	import type { StatisticsStateMachineState } from "./state-machine";

	export let state: StatisticsStateMachineState;
</script>

<Figure description="GitHub Stars">
	<Cite ariaLabel="GitHub Stars">
		{#if state.matches("loaded")}
			{state.context.gitHubStatistics.value.user.starredRepositories.totalCount}
		{:else if state.matches("failed")}
			{@html icons["alert-triangle"]?.toSvg()}
		{:else}
			<LoadingSpinner />
		{/if}
	</Cite>
</Figure>
