// source/statistics/StatisticsCite.tsx
import type { FunctionComponent, PropsWithChildren } from "react";
import styles from "./StatisticsCite.module.scss";

type Properties = {
	readonly description: string;
};

export const StatisticsCite: FunctionComponent<PropsWithChildren<Properties>> = (properties) => {
	const { description, children } = properties;

	return (
		<cite aria-label={description} className={styles.cite}>
			{children}
		</cite>
	);
};

// source/statistics/StatisticsCite.vue
<script setup lang="ts">
type Properties = {
	readonly description: string;
};

const { description } = defineProps<Properties>();
</script>

<template>
	<cite :aria-label="description">
		<slot />
	</cite>
</template>

<style lang="scss" scoped>
@use "../styles/variables";

cite {
	color: variables.$green;
	margin-top: 0.5rem;
	font-size: 1.125rem;
	font-weight: 700;
	font-style: normal;
}
</style>
