// source/statistics/YearsInBusiness.vue
<script setup lang="ts">
import StatisticsFigure from "./StatisticsFigure.vue";
import StatisticsCite from "./StatisticsCite.vue";

type Properties = {
	readonly yearsOfExperience: number;
};

const { yearsOfExperience } = defineProps<Properties>();
</script>

<template>
	<StatisticsFigure description="Experience">
		<StatisticsCite description="Years of experience">{{ yearsOfExperience }} yrs</StatisticsCite>
	</StatisticsFigure>
</template>

// source/statistics/YearsInBusiness.tsx
import type { FunctionComponent } from "react";
import { StatisticsFigure } from "./StatisticsFigure.js";
import { StatisticsCite } from "./StatisticsCite.js";

type Properties = {
	readonly yearsOfExperience: number;
};

export const YearsInBusiness: FunctionComponent<Properties> = (properties) => {
	const { yearsOfExperience } = properties;

	return (
		<StatisticsFigure description="Experience">
			<StatisticsCite description="Years of experience">
				{yearsOfExperience} {"yrs"}
			</StatisticsCite>
		</StatisticsFigure>
	);
};
